# Generated by Django 5.0.6 on 2024-06-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Процессор', 'Процессор'), ('Видеокарта', 'Видеокарта'), ('Оперативная память', 'Оперативная память'), ('Память', 'Память'), ('Материнская плата', 'Материнская плата'), ('Блок питания', 'Блок питания'), ('корпус', 'корпус')], max_length=20, null=True)),
                ('characteristics', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compatible_with', models.ManyToManyField(blank=True, to='pages.component')),
            ],
        ),
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Игровой', 'Игровой'), ('Офисный', 'Офисный'), ('Для дома', 'Для дома'), ('Профессиональный', 'Профессиональный'), ('Пользовательский', 'Пользовательский')], max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuild_frame', to='pages.component')),
                ('graphics_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuild_graphics_card', to='pages.component')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuild_memory', to='pages.component')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuild_motherboard', to='pages.component')),
                ('power_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuild_power_unit', to='pages.component')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuild_processor', to='pages.component')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuild_ram', to='pages.component')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pc_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pcbuild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
        ),
    ]
